### ISSUE TITLE
Error when starting txnvalidator with txnvalidator.js and using --restore flag

### ISSUE THREAD

**Issue by poppingtonic** [IntelLedger/sawtooth-dev-tools#2]
The command I ran:
```bash
vagrant@vagrant-ubuntu-trusty-64:/project/sawtooth-validator$ ./bin/txnvalidator --logfile=__screen__ --config /project/sawtooth-docs/source/tutorial/txnvalidator.js --restore

```

Results:
```bash
[11:57:44 INFO    validator_cli] validator started with arguments: ['./bin/txnvalidator', '--logfile=__screen__', '--config', '/project/sawtooth-docs/source/tutorial/txnvalidator.js', '--restore']
[11:57:44 WARNING validator_cli] validator pid is 1565
[11:57:44 WARNING validator_cli] unable to find locate key file /project/sawtooth-validator//keys/base000.wif
[11:57:44 INFO    validator] set administration node to 19ns29kWDTX8vNeHNzJbJy6S9HZiqHZyEE
[11:57:44 INFO    gossip_core] listening on IPv4Address(UDP, '127.0.0.1', 47518)
[11:57:44 INFO    global_store_manager] create blockstore from file /project/sawtooth-validator//data/base000_gs with flag c
[11:57:44 INFO    validator] starting ledger base000 with id 1KqHTXXQ at network address ('127.0.0.1', 47518)
[11:57:45 INFO    validator] ledger initialization complete
[11:57:45 INFO    journal_core] process initial transactions and blocks
[11:57:45 WARNING journal_core] restore ledger state from the backup data stores
[11:57:45 INFO    lottery_validator] register endpoint 1KqHTXXQ with name base000
[11:57:45 INFO    global_store_manager] add block 3540eb298f601c27 to the queue for loading
[11:57:45 INFO    global_store_manager] add block efe664df340dcdfd to the queue for loading
[11:57:45 INFO    global_store_manager] add block 5974127f48a255cc to the queue for loading
[11:57:45 INFO    global_store_manager] add block 95795243d1a18763 to the queue for loading
[11:57:45 INFO    global_store_manager] add block 5b0f18bdea7b1ce7 to the queue for loading
[11:57:45 INFO    global_store_manager] add block c39916ba5eb72678 to the queue for loading
[11:57:45 INFO    global_store_manager] add block 1b6ef33c82517427 to the queue for loading
[11:57:45 INFO    global_store_manager] add block abe36fc50d5bab1c to the queue for loading
[11:57:45 INFO    global_store_manager] add block f312b3e38930efd8 to the queue for loading
[11:57:45 INFO    global_store_manager] add block fa28be5e91be09db to the queue for loading
[11:57:45 INFO    global_store_manager] add block 5c15f3061cf4e08e to the queue for loading
[11:57:45 INFO    global_store_manager] add block 4673ffe2bc6fa07b to the queue for loading
[11:57:45 INFO    global_store_manager] add block 701d05610aa5b254 to the queue for loading
[11:57:45 INFO    global_store_manager] add block c027a68b9fd03b34 to the queue for loading
[11:57:45 INFO    global_store_manager] add block 8a57b63e8d023a2e to the queue for loading
[11:57:45 INFO    global_store_manager] add block bb2951c60c9c2041 to the queue for loading
[11:57:45 INFO    global_store_manager] add block 30976d890baeca69 to the queue for loading
[11:57:45 INFO    global_store_manager] add block ec9843ace58b87bc to the queue for loading
[11:57:45 INFO    global_store_manager] add block f54196602f10f201 to the queue for loading
[11:57:45 INFO    global_store_manager] add block fa10908016b4046b to the queue for loading
[11:57:45 INFO    global_store_manager] add block c2ac2f479557d417 to the queue for loading
[11:57:45 INFO    global_store_manager] add block be4bcf708973abc6 to the queue for loading
[11:57:45 INFO    global_store_manager] add block ca73612588cbc53d to the queue for loading
[11:57:45 INFO    global_store_manager] add block 4db61ca39c193258 to the queue for loading
[11:57:45 INFO    global_store_manager] add block 45e668097f935539 to the queue for loading
[11:57:45 INFO    global_store_manager] add block 47d008f27bac2a63 to the queue for loading
[11:57:45 INFO    global_store_manager] load block 47d008f27bac2a63 from storage
[11:57:45 ERROR   gossip_core] unexpected error handling message of type /ledger.transaction.EndpointRegistry/Transaction
Traceback (most recent call last):
  File "/project/sawtooth-core/gossip/gossip_core.py", line 574, in _dispatcher
    self.MessageHandlerMap[msg.MessageType][1](msg, self)
  File "/project/sawtooth-core/journal/messages/transaction_message.py", line 65, in transaction_message_handler
    journal.add_pending_transaction(msg.Transaction)
  File "/project/sawtooth-core/journal/journal_core.py", line 412, in add_pending_transaction
    self.PendingTransactionBlock = self.build_transaction_block()
  File "/project/sawtooth-core/journal/consensus/poet/poet_journal.py", line 76, in build_transaction_block
    self.MaximumTransactionsPerBlock)
  File "/project/sawtooth-core/journal/journal_core.py", line 914, in _preparetransactionlist
    store = self.GlobalStore.clone_block()
  File "/project/sawtooth-core/journal/journal_core.py", line 238, in GlobalStore
    return self.GlobalStoreMap.get_block_store(blkid)
  File "/project/sawtooth-core/journal/global_store_manager.py", line 170, in get_block_store
    self.require_store(blockid)
  File "/project/sawtooth-core/journal/global_store_manager.py", line 153, in require_store
    blockstore = prevstore.CloneBlock(blockinfo, True)
AttributeError: 'BlockStore' object has no attribute 'CloneBlock'
```

**Comment by jsmitchell** [comment]
It looks like we missed a couple of methods in our PEP8 renaming. One of the things we're working on is improving our unit test coverage to catch these sorts of things. I have a PR up to fix this that should be pushed up to github later today. In the meantime, here is the diff:

```
diff --git a/journal/global_store_manager.py b/journal/global_store_manager.py
index ba4db63..aa1867b 100644
--- a/journal/global_store_manager.py
+++ b/journal/global_store_manager.py
@@ -150,8 +150,8 @@ class GlobalStoreManager(object):
             logger.info('load block %s from storage', blockid)
             blockinfo = cbor.loads(self._persistmap[blockid])
             prevstore = self._blockmap[blockinfo['PreviousBlockID']]
-            blockstore = prevstore.CloneBlock(blockinfo, True)
-            blockstore.CommitBlock(blockid)
+            blockstore = prevstore.clone_block(blockinfo, True)
+            blockstore.commit_block(blockid)
             self._blockmap[blockid] = blockstore

     def get_block_store(self, blockid):
@@ -203,7 +203,7 @@ class GlobalStoreManager(object):
             blockid (str): Identifier associated with the block.
         """

-        blockstore = self.GetBlockStore(blockid)
+        blockstore = self.get_block_store(blockid)
         blockstore.flatten()

         self.flush_block_store(blockstore.PreviousBlockID)
```

**Comment by jsmitchell** [comment]
Ok, it's up there now. Can you fetch sawtooth-core and give it another try?

**Comment by poppingtonic** [comment]
It seems to work now. Thanks!
